# Generated by Django 6.0.4 on 2026-04-19 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_savedbacktest'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.asset'),
        ),
    ]
